[2022-03-01 16:53:19,609] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_outliers2.read_process_write_file manual__2022-03-01T16:53:17.052435+00:00 [queued]>
[2022-03-01 16:53:19,619] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_outliers2.read_process_write_file manual__2022-03-01T16:53:17.052435+00:00 [queued]>
[2022-03-01 16:53:19,619] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-01 16:53:19,620] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-01 16:53:19,620] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-01 16:53:19,638] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): read_process_write_file> on 2022-03-01 16:53:17.052435+00:00
[2022-03-01 16:53:19,644] {standard_task_runner.py:52} INFO - Started process 308 to run task
[2022-03-01 16:53:19,648] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_outliers2', 'read_process_write_file', 'manual__2022-03-01T16:53:17.052435+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag_outliers.py', '--cfg-path', '/tmp/tmph9623e7l', '--error-file', '/tmp/tmpdfj2n52u']
[2022-03-01 16:53:19,649] {standard_task_runner.py:77} INFO - Job 32: Subtask read_process_write_file
[2022-03-01 16:53:19,761] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_outliers2.read_process_write_file manual__2022-03-01T16:53:17.052435+00:00 [running]> on host 333967f3acd4
[2022-03-01 16:53:19,838] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/xcom.py:437: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  return query.delete()

[2022-03-01 16:53:19,852] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:126: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  session.merge(self)

[2022-03-01 16:53:19,873] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:162: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  tuple_(cls.dag_id, cls.task_id, cls.execution_date).notin_(subq1),

[2022-03-01 16:53:19,883] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:163: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ).delete(synchronize_session=False)

[2022-03-01 16:53:19,887] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_outliers2
AIRFLOW_CTX_TASK_ID=read_process_write_file
AIRFLOW_CTX_EXECUTION_DATE=2022-03-01T16:53:17.052435+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-01T16:53:17.052435+00:00
[2022-03-01 16:54:26,325] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2022-03-01 16:54:26,356] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=dag_outliers2, task_id=read_process_write_file, execution_date=20220301T165317, start_date=20220301T165319, end_date=20220301T165426
[2022-03-01 16:54:26,413] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-01 16:54:26,429] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dag.py:1079: SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
  return qry.value(DagModel.is_paused)

[2022-03-01 16:54:26,429] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dag.py:1079: SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
  return qry.value(DagModel.is_paused)

