[2022-03-01 18:23:32,692] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_outliers2.read_process_write_file manual__2022-03-01T18:23:31.083795+00:00 [queued]>
[2022-03-01 18:23:32,703] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_outliers2.read_process_write_file manual__2022-03-01T18:23:31.083795+00:00 [queued]>
[2022-03-01 18:23:32,703] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-01 18:23:32,704] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-01 18:23:32,704] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-01 18:23:32,721] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): read_process_write_file> on 2022-03-01 18:23:31.083795+00:00
[2022-03-01 18:23:32,727] {standard_task_runner.py:52} INFO - Started process 608 to run task
[2022-03-01 18:23:32,736] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_outliers2', 'read_process_write_file', 'manual__2022-03-01T18:23:31.083795+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag_outliers.py', '--cfg-path', '/tmp/tmpi_sokew3', '--error-file', '/tmp/tmpurn7r1dq']
[2022-03-01 18:23:32,737] {standard_task_runner.py:77} INFO - Job 44: Subtask read_process_write_file
[2022-03-01 18:23:32,805] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_outliers2.read_process_write_file manual__2022-03-01T18:23:31.083795+00:00 [running]> on host 083589a500f4
[2022-03-01 18:23:32,845] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/xcom.py:437: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  return query.delete()

[2022-03-01 18:23:32,855] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:126: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  session.merge(self)

[2022-03-01 18:23:32,867] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:162: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  tuple_(cls.dag_id, cls.task_id, cls.execution_date).notin_(subq1),

[2022-03-01 18:23:32,872] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:163: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ).delete(synchronize_session=False)

[2022-03-01 18:23:32,880] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_outliers2
AIRFLOW_CTX_TASK_ID=read_process_write_file
AIRFLOW_CTX_EXECUTION_DATE=2022-03-01T18:23:31.083795+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-01T18:23:31.083795+00:00
[2022-03-01 18:23:34,919] {logging_mixin.py:109} INFO - read success
[2022-03-01 18:23:35,231] {python.py:175} INFO - Done. Returned value was: None
[2022-03-01 18:23:35,246] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=dag_outliers2, task_id=read_process_write_file, execution_date=20220301T182331, start_date=20220301T182332, end_date=20220301T182335
[2022-03-01 18:23:35,285] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-01 18:23:35,303] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dag.py:1079: SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
  return qry.value(DagModel.is_paused)

[2022-03-01 18:23:35,304] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dag.py:1079: SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
  return qry.value(DagModel.is_paused)

